/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTodoRouteImport } from './routes/_auth/todo'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthPagesPageIdRouteImport } from './routes/_auth/pages/$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTodoRoute = AuthTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagesPageIdRoute = AuthPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthCalendarRoute
  '/settings': typeof AuthSettingsRoute
  '/todo': typeof AuthTodoRoute
  '/pages/$pageId': typeof AuthPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AuthCalendarRoute
  '/settings': typeof AuthSettingsRoute
  '/todo': typeof AuthTodoRoute
  '/': typeof AuthIndexRoute
  '/pages/$pageId': typeof AuthPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/todo': typeof AuthTodoRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/pages/$pageId': typeof AuthPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/settings'
    | '/todo'
    | '/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/calendar' | '/settings' | '/todo' | '/' | '/pages/$pageId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/calendar'
    | '/_auth/settings'
    | '/_auth/todo'
    | '/_auth/'
    | '/_auth/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/todo': {
      id: '/_auth/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AuthTodoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pages/$pageId': {
      id: '/_auth/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AuthPagesPageIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTodoRoute: typeof AuthTodoRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthPagesPageIdRoute: typeof AuthPagesPageIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCalendarRoute: AuthCalendarRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTodoRoute: AuthTodoRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthPagesPageIdRoute: AuthPagesPageIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
